
SQUIRREL=.
MAKE=make

sq32:
	cd squirrel; $(MAKE) sq32
	cd sqstdlib; $(MAKE) sq32
	cd sq; $(MAKE) sq32

sqprof:
	cd squirrel; $(MAKE) sqprof
	cd sqstdlib; $(MAKE) sqprof
	cd sq; $(MAKE) sqprof

sq64:
	cd squirrel; $(MAKE) sq64
	cd sqstdlib; $(MAKE) sq64
	cd sq; $(MAKE) sq64
